### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by wickedlaser** [wickedlaser/niborame#16]
### 実装予定の機能
- [ ] トップページの作成(店舗一覧表示)
- [ ] 新規店舗投稿機能
- [ ] 店舗情報の編集機能
- [ ] ラーメン店舗の情報取得機能
- [ ] タグフィルタリング機能

### 必要なページ
- [ ] トップページの作成
- [ ] 店舗詳細ページの作成
- [ ] ログインページの作成

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
MVPリリースに**管理画面の実装は不要**かと思いました。（データの削除、編集はコンソール上からできるため。）

上記の観点を踏まえて、再度ご確認のほどよろしくお願いします。

**Comment by wickedlaser** [comment]
## issueベースの開発

issueベースの開発にも関わらず確認不足で別のページを貼ってしまい、申し訳ありません。

指摘をいただいた通り管理画面を無くしてコンソールや投稿フォームから記事を追加する形にしようと思います。

最終的なリリース前に必要だと感じれば検討します。

**Comment by ky0613** [comment]
ご提出ありがとうございます。
以下、コメントになります。

----

ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5以上を付けているように見受けられました。
ストーリーポイント1,2になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by wickedlaser** [comment]
アドバイスありがとうございます。

google map apiの実装について分からない部分が多かったのですが、自分なりに調べて設定と実装の2つに分けました。

ストーリーポイントが小さくなるように変更しましたので確認お願いします

**Comment by kashiwagi-rena** [comment]
お疲れ様です。

下記スクショの赤枠の方を押下していただき、projectsの紐付けを行いましょう。
![スクリーンショット 2024-06-29 14 34 23](https://github.com/wickedlaser/niborame/assets/108249057/775d3fed-4671-4645-b2d1-566d9714776e)

実装について分からなかった部分を調べてくださり、ありがとうございます。
調べた際に参考になった記事は、issueに紐付けを行ってくださると嬉しいです。

環境構築の際に、Bootstrap等のCSSやJSのフレームワークを使用される場合はインストールの検討もお願いいたします。

**Comment by wickedlaser** [comment]
アドバイスありがとうございます。

Projectsを追加しました。
そして、参考にした記事をissueにURLとともに貼りました。
レビューお願いします。

node_modulesを何度インストールしてもフォルダ内が空になるがコンテナに入ってデータを確認するとインストールされているという現象が発生しました。
そこで、CDNでBootstrapを使用するようにしたところ動作しています。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
以下コメントになります。

---

- 店舗情報の一覧表示機能
- 新規店舗投稿機能
- ラーメン店舗の情報取得機能

上記のissueが見当たらなかったのですが、ご確認いただけますでしょうか。

**Comment by wickedlaser** [comment]
文章の説明が分かりづらくて申し訳ありませんでした。

以下のように変更しました。
---

・店舗情報の一覧表示機能→トップページの店舗一覧表示に変更
・管理画面からの投稿機能→新規店舗投稿機能
・ラーメン店舗の情報取得機能→Google Maps APIの実装に変更

in progressやdoneに移動させていたものを一旦todoへ戻しました。
確認お願いします。

**Comment by shota-hope** [comment]
修正ありがとうございます。LGTMです！
少しタスクが大きく感じる箇所もあるので、開発を進めながらも常にタスク分割できないかを考えて、適宜修正していくことを心がけて進めるようにすると良いと思います。
