### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by wickedlaser** [wickedlaser/niborame#26]
## 各種情報
煮干(にぼ)サーチ
サービスURL:https://niborame.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ラーメン屋の位置を表示する地図機能
- [x] ラーメン屋の詳細情報
- [x] 店舗名から画像を取得し表示する機能
- [x] ラーメン屋が一覧で見れるトップページ

予定していたものはトップページと店舗詳細ページだったので、その付随機能の追加などは実装できていると思います。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
- [x] renderでのデプロイは無料枠だと制限が多く不具合が多かったのでfly.ioに変更
- [x] 本リリースでタグによる店舗絞り込み機能を実装する予定だったがMVP時点で実装
- [x] 店舗一覧ページを作成する予定だったがトップページと機能が被るため却下
- [x]  MVPリリース前の面談にしてseedsから店舗を追加する方法を勧められたため投稿機能は却下
- [x] 営業時間の情報は取得する予定がなかったがあった方が良いと思い追加 

## サービスイメージがわかるようなスクリーンショット等

・トップページ
[![Image from Gyazo](https://i.gyazo.com/ade13b675378c33ab95842b1559add43.jpg)](https://gyazo.com/ade13b675378c33ab95842b1559add43)

・店舗情報ページの営業時間や地図表示
[![Image from Gyazo](https://i.gyazo.com/daeaf40687aba0bb6fff49c009dc8827.jpg)](https://gyazo.com/daeaf40687aba0bb6fff49c009dc8827)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
